apiVersion: v1
kind: Service
metadata:
  name: zebra-aws
  namespace: zebra-aws
spec:
  selector:
    app: zebra-aws
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
  externalIPs:
    - 34.75.26.228
   
  type: NodePort
